[package]
name = "eklet-agent"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

#[[package.metadata.build-package.external-files]]
#url = "https://github.com/containerd/containerd/archive/v1.4.4/containerd-1.4.4.tar.gz"
#sha512 = "f09930d19f53381d86cf522954458ecc949f15a0c6a49f990bdb61fe19afee075356338998ed84bd756f16ba85211f55f9c638de8b7083d71e24d8e87335e070"

[build-dependencies]
glibc = { path = "../glibc" }
