[package]
name = "release"
version = "0.0.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[build-dependencies]
growpart = { path = "../growpart" }
libstd-rust = {path = "../libstd-rust"}
